SELECT INFO.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO INFO LEFT JOIN ITEM_TREE TREE
ON INFO.ITEM_ID = TREE.ITEM_ID
WHERE PARENT_ITEM_ID IN (
    SELECT INFO.ITEM_ID
    FROM ITEM_INFO INFO
    WHERE INFO.RARITY = 'RARE'
)
ORDER BY 1 DESC;