SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK AS B
JOIN (SELECT *
FROM BOOK_SALES
-- WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
WHERE DATE_FORMAT(SALES_DATE,"%Y-%m") = "2022-01") AS S 
ON B.BOOK_ID = S.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC;